In [1]:
print("Mohammad")

Mohammad


In [2]:
import numpy as np


In [4]:
number_1 = np.array(10)
number_1_ndim = number_1.ndim
print(number_1,"\n","number ndim:",number_1_ndim)

10 
 number ndim: 0


In [6]:
number_2 = np.array([1,2,3,4,5,6,] )
number_2_ndim = number_2.ndim
print(number_2,"\n","number ndim:",number_2_ndim)

[1 2 3 4 5 6] 
 number ndim: 1


In [8]:
number_3 = np.array([[6,5,4],[3,2,1,]])
number_3_ndim = number_3.ndim
print(number_3,"\n","number ndim:",number_3_ndim)

[[6 5 4]
 [3 2 1]] 
 number ndim: 2


In [9]:
number_4 = np.array([[[7,8,9],[10,11,12],[13,14,15]]])
number_4_ndim = number_4.ndim
print(number_4,"\n","number ndim:",number_4_ndim)

[[[ 7  8  9]
  [10 11 12]
  [13 14 15]]] 
 number ndim: 3


In [10]:
number_5 = np.array([[[[16,17,18],[19,20,21],[22,23,24],[25,26,27]]]])
number_5_ndim = number_5.ndim
print(number_5,"\n","number ndim:",number_5_ndim)

[[[[16 17 18]
   [19 20 21]
   [22 23 24]
   [25 26 27]]]] 
 number ndim: 4


In [11]:
number_6 = np.array([[[[[28,29,30],[31,32,33],[34,35,36],[37,38,39],[40,41,42]]]]])
number_6_ndim = number_6.ndim
print(number_6,"\n","number ndim:",number_6_ndim)

[[[[[28 29 30]
    [31 32 33]
    [34 35 36]
    [37 38 39]
    [40 41 42]]]]] 
 number ndim: 5


In [12]:
number_7 = np.array([1,2,3],ndmin = 1)
number_7

array([1, 2, 3])

In [13]:
number_8 = np.array([4,5,6],ndmin = 2)
number_8

array([[4, 5, 6]])

In [14]:
number_9 = np.array([7,8,9],ndmin = 15)
number_9

array([[[[[[[[[[[[[[[7, 8, 9]]]]]]]]]]]]]]])