In [2]:
import numpy as np
# ایجاد یک ارایه و  اسلیس کردن آن 
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(arr[2:7])

print(arr[2::2])

print(arr[5:0:-1])

print(arr[4])

print(arr[:])

[3 4 5 6 7]
[3 5 7 9]
[6 5 4 3 2]
5
[ 1  2  3  4  5  6  7  8  9 10]


In [37]:
# اجاد ماتریس 10*10 و بیرون کشیدن ماتریس های کوچکه در آن
matrix = np.random.randint(1, 10, (10, 10))

print(matrix)


[[6 5 5 9 9 2 6 6 3 3]
 [2 6 7 8 2 8 5 2 1 8]
 [1 9 4 2 4 4 4 2 9 6]
 [4 8 3 2 8 9 2 1 4 2]
 [1 8 1 3 6 1 1 1 8 2]
 [7 5 5 6 1 7 6 8 6 9]
 [4 8 2 4 7 6 6 9 1 9]
 [5 9 8 6 5 2 9 7 9 4]
 [5 2 8 6 2 4 4 5 4 7]
 [9 1 5 6 4 5 7 9 9 3]]


In [42]:
print (matrix[0:5,0:5])

[[6 5 5 9 9]
 [2 6 7 8 2]
 [1 9 4 2 4]
 [4 8 3 2 8]
 [1 8 1 3 6]]


In [44]:
print (matrix[0:5,5:])

[[2 6 6 3 3]
 [8 5 2 1 8]
 [4 4 2 9 6]
 [9 2 1 4 2]
 [1 1 1 8 2]]


In [46]:
print (matrix[5:,0:5])

[[7 5 5 6 1]
 [4 8 2 4 7]
 [5 9 8 6 5]
 [5 2 8 6 2]
 [9 1 5 6 4]]


In [48]:
print (matrix[5:,5:])

[[7 6 8 6 9]
 [6 6 9 1 9]
 [2 9 7 9 4]
 [4 4 5 4 7]
 [5 7 9 9 3]]


In [50]:
print (matrix[2:7,2:7])

[[4 2 4 4 4]
 [3 2 8 9 2]
 [1 3 6 1 1]
 [5 6 1 7 6]
 [2 4 7 6 6]]


In [51]:
#ایجاد ماتریس 1000*1000 بصورت خودکار
matrix = np.random.randint(1, 100, (1000, 1000))
print(matrix)

[[65 30 89 ...  1 42 48]
 [88 81 86 ... 58 10 59]
 [10 70 62 ... 38 67 78]
 ...
 [81 14 37 ... 89 64 90]
 [60 40 24 ... 49 26  2]
 [76  6 13 ... 76 81 19]]
