In [16]:
import numpy as np
number_1 = np.array([1,2,3,4,5,6,] )
number_1_ndim = number_1.ndim
print(number_1,"\n","number ndim:",number_1_ndim)

[1 2 3 4 5 6] 
 number ndim: 1


In [17]:
number_2 = np.array([[6,5,4],[3,2,1,]])
number_2_ndim = number_2.ndim
print(number_2,"\n","number2 ndim:",number_2_ndim)

[[6 5 4]
 [3 2 1]] 
 number2 ndim: 2


In [18]:
number_3 = np.array([[[7,8,9],[10,11,12],[13,14,15]]])
number_3_ndim = number_3.ndim
print(number_3,"\n","number3 ndim:",number_3_ndim)

[[[ 7  8  9]
  [10 11 12]
  [13 14 15]]] 
 number3 ndim: 3


In [19]:
number_4 = np.array([[[[16,17,18],[19,20,21],[22,23,24],[25,26,27]]]])
number_4_ndim = number_4.ndim
print(number_4,"\n","number4 ndim:",number_4_ndim)

[[[[16 17 18]
   [19 20 21]
   [22 23 24]
   [25 26 27]]]] 
 number4 ndim: 4


In [20]:
number_5 = np.array([[[[[28,29,30],[31,32,33],[34,35,36],[37,38,39],[40,41,42]]]]])
number_5_ndim = number_5.ndim
print(number_5,"\n","number5 ndim:",number_5_ndim)

[[[[[28 29 30]
    [31 32 33]
    [34 35 36]
    [37 38 39]
    [40 41 42]]]]] 
 number5 ndim: 5


In [32]:
number_6 = np.array([1,2,3],ndmin = 1)
number_6

array([1, 2, 3])

In [33]:
number_7 = np.array([4,5,6],ndmin = 2)
number_7

array([[4, 5, 6]])

In [38]:
number_8 = np.array([7,8,9],ndmin = 15)
number_8

array([[[[[[[[[[[[[[[7, 8, 9]]]]]]]]]]]]]]])